### ISSUE TITLE
Tomcat fails to start /idrop-web2-production-2.1.0

### ISSUE THREAD

**Issue by donpellegrino** [DICE-UNC/idrop#125]
When attempting to start "/idrop-web2-production-2.1.0" on Tomcat 7.0.33, Red Hat Enterprise Linux 6.6 (RHEL6) the following message is reported by the Tomcat Web Application Manager:

FAIL - Application at context path /idrop-web2 could not be started

The precompiled .war file from https://code.renci.org/gf/download/frsrelease/221/2508/idrop-web2.war was deployed to Tomcat successfully. In addition, /etc/idrop-web/idrop-web-config2.groovy was in place before attempting to start the application. Many errors were reported to /var/log/tomcat/catalina.out with a snip of some that seem relevant below:

May 26, 2015 10:15:03 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat/webapps/idrop-web2.war
May 26, 2015 10:15:06 AM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
2015-05-26 10:15:08,052 [http-bio-8080-exec-13] WARN  support.XmlWebApplicationContext  - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplication' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.UnsupportedClassVersionError: org/irods/jargon/core/exception/JargonException : Unsupported major.minor version 51.0 (unable to load class org.irods.jargon.core.exception.JargonException)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:856)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:805)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.UnsupportedClassVersionError: org/irods/jargon/core/exception/JargonException : Unsupported major.minor version 51.0 (unable to load class org.irods.jargon.core.exception.JargonException)
        at java.lang.Class.forName(Class.java:274)
        ... 5 more
2015-05-26 10:15:08,055 [http-bio-8080-exec-13] ERROR context.ContextLoader  - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplication' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.UnsupportedClassVersionError: org/irods/jargon/core/exception/JargonException : Unsupported major.minor version 51.0 (unable to load class org.irods.jargon.core.exception.JargonException)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:856)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:805)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.UnsupportedClassVersionError: org/irods/jargon/core/exception/JargonException : Unsupported major.minor version 51.0\
 (unable to load class org.irods.jargon.core.exception.JargonException)
        at java.lang.Class.forName(Class.java:274)
        ... 5 more
2015-05-26 10:15:08,056 [http-bio-8080-exec-13] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'grailsApplication' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.UnsupportedClassVersionError: org/irods/jargon/core/exception/JargonException : Unsupported major.minor version 51.0 (unable to load class org.irods.jargon.core.exception.JargonException)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplication' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.UnsupportedClassVersionError: org/irods/jargon/core/exception/JargonException : Unsupported major.minor version 51.0 (unable to load class org.irods.jargon.core.exception.JargonException)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:856)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:805)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.UnsupportedClassVersionError: org/irods/jargon/core/exception/JargonException : Unsupported major.minor version 51.0 (unable to load class org.irods.jargon.core.exception.JargonException)
        at java.lang.Class.forName(Class.java:274)
        ... 5 more

**Comment by donpellegrino** [comment]
Even though Tomcat reports the application as "/idrop-web2-production-2.1.0" it looks like it is the .war file from Release 231 at https://code.renci.org/gf/project/irodsidrop/frs/?action=FrsReleaseView&release_id=231 with the following MD5:

# md5sum idrop-web2.war
fce8ca223da8b65239bf3eaad3876184  idrop-web2.war

**Comment by michael-conway** [comment]
that looks an awful lot like a jdk issue.  Try 1.7+, I bet you are on 1.5!

MC

**Comment by donpellegrino** [comment]
That was it. I was using java-1.6.0-openjdk-1.6.0.35-1.13.7.1.el6_6.x86_64. I upgraded it to java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64 and then selected 1.8 as the default with /usr/sbin/alternatives --config java. The pre-compiled idrop-web2.war now seems to be working. Thanks!

**Comment by michael-conway** [comment]
great thanks!

We're expecting big improvements with the iRODS cloud browser project, since we have been able to hire a web front end dev/graphics designer. We'll be previewing work in progress at the UG Meeting
