### ISSUE TITLE
Selecting Preferences from dropdown does nothing

### ISSUE THREAD

**Issue by jerry57** [DICE-UNC/idrop#98]
if you have iDrop launched, click the "check mark" and then select Preferences from the list
Note that Nothing happens at all

Running through SwingExplorer is showing a stacktrace about missing resource bundle

Here is the trace
2015-02-06 08:34:07,861 16657 [SwingWorker-pool-2-thread-1] INFO  org.irods.jargon.idrop.desktop.systraygui.viscomponents.IRODSNode  - >>> total query time = 1423236847804
Exception in thread "AWT-EventQueue-0" java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key IDROPConfigurationPanel.showWithinFileProgress.text
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
	at org.irods.jargon.idrop.desktop.systraygui.IDROPConfigurationPanel.initComponents(IDROPConfigurationPanel.java:495)
	at org.irods.jargon.idrop.desktop.systraygui.IDROPConfigurationPanel.<init>(IDROPConfigurationPanel.java:64)
	at org.irods.jargon.idrop.desktop.systraygui.iDrop.actionPerformed(iDrop.java:873)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at org.swingexplorer.edt_monitor.EDTDebugQueue.dispatchEvent(EDTDebugQueue.java:252)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-02-06 08:34:15,522 24318 [Timer-4] INFO  org.irods.jargon.conveyor.core.ConveyorQueueTimerTask  - timer task running
2015-02-06 08:34:15,523 24319 [Timer-4] INFO  org.irods.jargon.conveyor.core.ConveyorQueueTimerTask  - timer task firing...dequeue if available

This was with build:
v2.0.1-RC1-002

**Comment by michael-conway** [comment]
cool.

Yes, there may be a few here and there.  I’ll do a drop in a few minutes, and we can pass the installs via the GForge download page.

MC

**Comment by michael-conway** [comment]
this is another resource bundle gotcha...will include this fix in the next push
